# Generated by Django 4.1.13 on 2023-12-02 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubbing", "0002_remove_review_date_posted_remove_review_text_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="review",
            table="ratings",
        ),
    ]
