# Generated by Django 4.1.13 on 2023-12-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubbing", "0005_alter_event_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="type",
            field=models.CharField(max_length=255),
        ),
    ]
